version: '3'

services:
  backend:
    image: vanchez98/django_with_sql:latest
    container_name: internship-backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=internship-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=internshipDB
      - DATABASE_USER=root
      - DATABASE_PASSWORD=SecretPassword

networks:
  default:
    name: internship-network
    driver: bridge